
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox9;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label Uri;

	private global::Gtk.Entry textURI;

	private global::Gtk.ComboBox comboUserName;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView dataNodeView;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button btnAddUser;

	private global::Gtk.Button btnShowUsers;

	private global::Gtk.Button btnUpdUser;

	private global::Gtk.Button btnDeleteUser;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Uri = new global::Gtk.Label();
		this.Uri.Name = "Uri";
		this.Uri.LabelProp = global::Mono.Unix.Catalog.GetString("URI:");
		this.hbox3.Add(this.Uri);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Uri]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.textURI = new global::Gtk.Entry();
		this.textURI.CanFocus = true;
		this.textURI.Name = "textURI";
		this.textURI.IsEditable = true;
		this.textURI.InvisibleChar = '●';
		this.hbox3.Add(this.textURI);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.textURI]));
		w3.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.comboUserName = global::Gtk.ComboBox.NewText();
		this.comboUserName.Name = "comboUserName";
		this.hbox3.Add(this.comboUserName);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.comboUserName]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox9.Add(this.hbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.dataNodeView = new global::Gtk.NodeView();
		this.dataNodeView.CanFocus = true;
		this.dataNodeView.Name = "dataNodeView";
		this.GtkScrolledWindow.Add(this.dataNodeView);
		this.vbox9.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.GtkScrolledWindow]));
		w7.Position = 1;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnAddUser = new global::Gtk.Button();
		this.btnAddUser.CanFocus = true;
		this.btnAddUser.Name = "btnAddUser";
		this.btnAddUser.UseUnderline = true;
		this.btnAddUser.Label = global::Mono.Unix.Catalog.GetString("Adicionar");
		this.hbox5.Add(this.btnAddUser);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnAddUser]));
		w8.Position = 0;
		w8.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnShowUsers = new global::Gtk.Button();
		this.btnShowUsers.CanFocus = true;
		this.btnShowUsers.Name = "btnShowUsers";
		this.btnShowUsers.UseUnderline = true;
		this.btnShowUsers.Label = global::Mono.Unix.Catalog.GetString("Mostrar todos");
		this.hbox5.Add(this.btnShowUsers);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnShowUsers]));
		w9.Position = 1;
		w9.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnUpdUser = new global::Gtk.Button();
		this.btnUpdUser.CanFocus = true;
		this.btnUpdUser.Name = "btnUpdUser";
		this.btnUpdUser.UseUnderline = true;
		this.btnUpdUser.Label = global::Mono.Unix.Catalog.GetString("Editar");
		this.hbox5.Add(this.btnUpdUser);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnUpdUser]));
		w10.Position = 2;
		w10.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.btnDeleteUser = new global::Gtk.Button();
		this.btnDeleteUser.CanFocus = true;
		this.btnDeleteUser.Name = "btnDeleteUser";
		this.btnDeleteUser.UseUnderline = true;
		this.btnDeleteUser.Label = global::Mono.Unix.Catalog.GetString("Remover");
		this.hbox5.Add(this.btnDeleteUser);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.btnDeleteUser]));
		w11.Position = 3;
		w11.Fill = false;
		this.vbox9.Add(this.hbox5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox5]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.Add(this.vbox9);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 817;
		this.DefaultHeight = 528;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
